<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="../css/style.css">
</head>

<body>
    <section class="nav">
        <h1>Acceuil du blog</h1>
        <h2>les derniers articles postes</h2>
    </section>

    <h3>les nouvelles de Tante URSULE</h3>
    <section class="main">
        <article>
            <div class="yellow-bloc">
                <h4>les nouveauté de Téris 64</h4>
                <h5>Dans la catégorie :<span>Jeux videos </span></h5>
            </div>
            <div>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla veniam repellendus facere itaque ad autem at quas natus beatae dicta cum, sunt sed odio placeat in veritatis quod officiis deserunt.
                <button type="submit">Lire la suite</button>
            </div>
            <div  class="bloc-gray">
                Redigé Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla veniam repellendus 
            </div>
        </article>
        <article>
            <div class="yellow-bloc">
                <h4>Java script et le réchauffement climatique</h4>
                <h5>Dans la catégorie :<span>Javascript & sociéte </span></h5>
            </div>
            <div>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla veniam repellendus facere itaque ad autem at quas natus beatae dicta cum, sunt sed odio placeat in veritatis quod officiis deserunt.
                <button type="submit">Lire la suite</button>
            </div>
            <div class="bloc-gray">
                Redigé Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla veniam repellendus 
            </div>
        </article>
    </section>
</body>

</html>