<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="../css/style.css">
</head>

<body>
    <section class="nav">
        <h1>Acceuil du blog</h1>
        <h2>les derniers articles postes</h2>
    </section>

    <h3>les nouvelles de Tante URSULE</h3>
    <section class="main">

        <article>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eaque doloribus assumenda cumque modi molestias
                illo quia ducimus, voluptatum corrupti id nihil aliquam dolor? Nulla optio minima aliquid deserunt rem
                reiciendis!</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eaque doloribus assumenda cumque modi molestias
                illo quia ducimus, voluptatum corrupti id nihil aliquam dolor? Nulla optio minima aliquid deserunt rem
                reiciendis!</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eaque doloribus assumenda cumque modi molestias
                illo quia ducimus, voluptatum corrupti id nihil aliquam dolor? Nulla optio minima aliquid deserunt rem
                reiciendis!</p>
        </article>
        <article>
            <h3>Liste des commentaires</h3>
            <div class="black-bloc">
                REDIGEE PAR <strong></strong>
            </div>
            <div class="yellow-bloc">
                <form action="" method="post">
                <h4>Nouveau commentaire</h4>
                <label for="">pseudo</label>
                <input type="text" name="pseudo" id="psudo">
                <br>
                <label for="">commentaire</label>
                <textarea name="comment" id="" cols="30" rows="4"></textarea>
                
                <div>
                    <button type="submit">Annuler</button>
                    <button type="submit">Ajouter</button>
                    
                </div>
            </div>
            </form>
          
        </article>
    </section>
</body>

</html>